[package]
name = "celtic_names"
version = "0.1.5"
authors = ["Adilson Neto <almeidneto@gmail.com>"]
edition = "2018"

[dependencies]
ureq = "1.0.0"
scraper = "0.12.0"
rand = "0.8.0"
clap = "2.33.0"
markov = "1.0.2"
dont_disappear = "3.0.0"