[package]
name = "celtic_names"
version = "0.1.1"
authors = ["Adilson Neto <almeidneto@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
scraper = "0.10.0"
rand = "0.6.5"
clap = "2.33.0"
markov = "1.0.2"